version: '3.8'

services:
  # Service for authen-service
  postgres_authen:
    container_name: postgres_authen_container
    image: postgres:${POSTGRES_VERSION:-16}
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTHEN:-sa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTHEN:-123}
      POSTGRES_DB: ${POSTGRES_DATABASE_AUTHEN:-authen_service_db}
      PGDATA: /data/postgres
    volumes:
      - postgres_authen:/data/postgres
    ports:
      - "${POSTGRES_PORT_AUTHEN:-5432}:5432"
    networks:
      - microservice-network
    restart: unless-stopped

  # Service for route-service
  postgres_route:
    container_name: postgres_route_container
    image: postgres:${POSTGRES_VERSION_ROUTE:-16}
    environment:
      POSTGRES_USER: ${POSTGRES_USER_ROUTE:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ROUTE:-12345}
      POSTGRES_DB: ${POSTGRES_DATABASE_ROUTE:-route_service_db}
      PGDATA: /data/postgres
    volumes:
      - postgres_route:/data/postgres
    ports:
      - "${POSTGRES_PORT_ROUTE:-5435}:5432"
    networks:
      - microservice-network
    restart: unless-stopped


# Kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-cluster-network

  kafka-1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-cluster-network

  kafka-2:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9093:9093"
    networks:
      - kafka-cluster-network

  kafka-3:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9094:9094"
    networks:
      - kafka-cluster-network

networks:
  kafka-cluster-network:
    driver: bridge

  microservice-network:
    driver: bridge

volumes:
  postgres_authen:
  postgres_route: