version: '3.8'

services:
  postgres:
    container_name: route_service_container
    image: postgres:${POSTGRES_VERSION:-16}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_DB: ${POSTGRES_DATABASE:-route_service_db}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    networks:
      - microservice-network
    restart: unless-stopped

networks:
  microservice-network:
     driver: bridge

volumes:
    postgres: